### ISSUE TITLE
CheckList 1

### ISSUE THREAD

**Issue by newordn** [Noutchiadiane/gheproject#1]
- [ ] le favicon du site faut l'ajouter
- [ ] le font size de la premiere ligne du logo doit etre le meme que celui de la seconde ligne
- [ ] la navlink pour la localisation tu n'a pas ajouter
- [ ] au niveau de service dans la navbar il serait bien qu'un menu deroulant face apparaitre la liste de tout les services
- [ ] dans le premier slide faut lister tout les services (hydraulic hoses .... par juste 9)
- [ ] le slide doit bouger de lui meme sans avoir a cliquer dessus
- [ ]  Pourquoi mettre la meme image pourtant tu dis ne pas pouvoir toute les images 
![Capture](https://user-images.githubusercontent.com/25830485/102133369-496db180-3e55-11eb-8936-a632366908ac.PNG)
- [ ] Quick help, Country ,events faut enlever ou remplacer par quelque choses de plus approprier
- [ ] la partie nos projets faut mettre a jour
- les chiffres la aussi et le footer (faut mettre un lien vers la localisation a l'interieur)
- assure toi de mettre toute les informations du word a l'interieur de ce site (toute les informations)
